dist: trusty
sudo: required

language: python
python:
    - "2.7"

virtualenv:
    system_site_packages: true


branches:
    only:
        - master
    except:
        - eg-other


before_install:
    - sudo apt-get update -qq
    - sudo apt-get install unzip -qq -y

    - sudo apt-get install g++ -qq -y
    - sudo apt-get install cmake git make -qq -y
    - sudo apt-get install python-dev -qq -y

    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh -q
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update conda -q -y
    - conda install conda-build -y -q

    - cmake --version
    - gcc --version
    - cc --version
    - c++ --version
    - ld --version

# ###### Compile bempp from scratch
#
#
before_script:
    - bash .compile_hack_to_bypass_log_limit.sh
#
#
# ##### Done from scratch.

    # Gmsh is required to pass some tests
    - sudo apt-get install gmsh -qq -y

# ##### Compile using conda
#
#
script:
    - conda build master --python 3.5 > conda.log
#
#
# ##### Done.


#
# This after_* is not doing what I expect
#

after_success:
    - echo "Done."

after_failure:
    - echo "Failed."
