package:
    name: bempp
    version: "3.0.0"

build:
    number: 0

source:
    fn: v3.0.0.tar.gz
    url: https://github.com/bempp/bempp/archive/v3.0.0.tar.gz
    md5: b032e2b9ff545d649178d142c3aa9564

requirements:
    build:
    # CMake: version higher than 3.4 breaks the compilation of Dune
    # CMake: version different that 3.0.2 leads to troubles with TBB
        - python
        - system
        - cython
        - numpy
        - mkl

    run :
        - ipython
        - numpy
        - scipy
        - matplotlib
        - pyqt
        - mkl

test:
    imports:
        - bempp
        - bempp.api
    # commands:
    #     - python laplace.py
    #     - python scattering.py
    #     - python oscr.py
    #     - python maxwell.py


about:
    home: http://www.bempp.org/
    license: MIT
    summary: BEM++ - Python boundary element library
